### ISSUE TITLE
Standardize config and cred provider access paths?

### ISSUE THREAD

**Issue by anitarua** [momentohq/client-sdk-rust#286]
Chris: should we standardize configs and cred providers so that they both come from a module (`topics::configurations::*`) or they both come from a struct (`CredentialProvider::from_env_var`)?

making configs into structs would produce`cache::configurations:Laptop::latest()` instead of `cache::configurations:laptop::latest()`

making credential provider into a module would be a bigger change and not even sure it's desirable given the struct contains the endpoints:
```
pub struct CredentialProvider {
    pub(crate) auth_token: String,
    pub(crate) control_endpoint: String,
    pub(crate) cache_endpoint: String,
    pub(crate) token_endpoint: String,
}
```

**Comment by malandis** [comment]
The `CredentialProvider` makes sense to be a struct since it encapsulates data and has static factories (`from_env_var`, `from_api_key_string`).

The pre-built configurations are a bit spread out in the various modules. These namespaces all have a `latest` function, so that is a common expectation we should capture. We can make a trait `PreBuiltConfiguration` that requires `latest` and `v1` functions that return `impl Into<Configuration>`. We can then define structs for each of `Laptop`, `Lambda`, etc that implement these.
